-- Standardize entity names in contributivo table
UPDATE landing.contributivo
SET "Nombre de la entidad" = 
    CASE
        WHEN "Nombre de la entidad" = 'ALIANSALUD EPS S.A.' THEN 'ALIANSALUD'
        WHEN "Nombre de la entidad" = 'ALIANZA MEDELLIN ANTIOQUIA EPS S.A.S. SAVIA SALUD EPS -CM' THEN 'SAVIA SALUD'
        WHEN "Nombre de la entidad" = 'ASOCIACIÓN DE CABILDOS INDÍGENAS DEL CESAR Y GUAJIRA DUSAKAWI A.R.S.I. -CM' THEN 'DUSAKAWI EPSI'
        WHEN "Nombre de la entidad" = 'ASMET SALUD EPS S.A.S. -CM' THEN 'ASMET SALUD EPS'
        WHEN "Nombre de la entidad" = 'ASOCIACION MUTUAL SER EMPRESA SOLIDARIA DE SALUD ENTIDAD PROMOTORA DE SALUD - MUTUAL SER EPS' THEN 'MUTUAL SER EPS'
        WHEN "Nombre de la entidad" = 'ASOCIACION MUTUAL SER EMPRESA SOLIDARIA DE SALUD ENTIDAD PROMOTORA DE SALUD - MUTUAL SER EPS -CM' THEN 'MUTUAL SER EPS'
        WHEN "Nombre de la entidad" = 'CAJACOPI EPS S.A.S -CM' THEN 'CAJACOPI EPS'
        WHEN "Nombre de la entidad" = 'ASOCIACIÓN INDÍGENA DEL CAUCA A.I.C. EPSI -CM' THEN 'ASOCIACIÓN INDÍGENA DEL CAUCA'
        WHEN "Nombre de la entidad" = 'CAJA DE COMPENSACIÓN FAMILIAR COMPENSAR' THEN 'COMPENSAR'
        WHEN "Nombre de la entidad" = 'CAJA DE COMPENSACIÓN FAMILIAR DEL CHOCÓ -CM' THEN 'COMFACHOCÓ'
        WHEN "Nombre de la entidad" = 'CAJA DE COMPENSACIÓN FAMILIAR DEL ORIENTE COLOMBIANO COMFAORIENTE -CM' THEN 'COMFAORIENTE'
        WHEN "Nombre de la entidad" = 'CAJA DE COMPENSACION FAMILIAR DEL VALLE DEL CAUCA COMFENALCO VALLE DE LA GENTE' THEN 'COMFENALCO'
        WHEN "Nombre de la entidad" = 'CAPITAL SALUD ENTIDAD PROMOTORA DE SALUD DEL RÉGIMEN SUBSIDIADO SAS CAPITAL SALUD EPS-S S.A.S. -CM' THEN 'CAPITAL SALUD'
        WHEN "Nombre de la entidad" = 'CAPRESOCA E.P.S. -CM' THEN 'CAPRESOCA EPS'
        WHEN "Nombre de la entidad" = 'COOSALUD EPS S.A.' THEN 'COOSALUD EPS'
        WHEN "Nombre de la entidad" = 'COOSALUD EPS S.A. -CM' THEN 'COOSALUD EPS'
        WHEN "Nombre de la entidad" = 'EMPRESA PROMOTORA DE SALUD INDÍGENA ANAS WAYUU EPSI -CM' THEN 'ANAS WAYUU EPSI'
        WHEN "Nombre de la entidad" = 'EMPRESAS PUBLICAS DE MEDELLIN - DEPARTAMENTO MEDICO' THEN 'EPM-DPM'
        WHEN "Nombre de la entidad" = 'EMSSANAR S.A.S. -CM' THEN 'EMSSANAR'
        WHEN "Nombre de la entidad" = 'ENTIDAD PROMOTORA DE SALUD MALLAMAS EPSI -CM' THEN 'MALLAMAS EPSI'
        WHEN "Nombre de la entidad" = 'ENTIDAD PROMOTORA DE SALUD SANITAS S.A.S.' THEN 'SANITAS'
        WHEN "Nombre de la entidad" = 'ENTIDAD PROMOTORA DE SALUD SERVICIO OCCIDENTAL DE SALUD S.A. S.O.S.' THEN 'EPS S.O.S.'
        WHEN "Nombre de la entidad" = 'EPS FAMILIAR DE COLOMBIA S.A.S. -CM' THEN 'EPS FAMILIAR DE COLOMBIA'
        WHEN "Nombre de la entidad" = 'EPS FAMISANAR S.A.S.' THEN 'FAMISANAR'
        WHEN "Nombre de la entidad" = 'EPS SURAMERICANA S.A.' THEN 'SURA'
        WHEN "Nombre de la entidad" = 'FONDO PASIVO SOCIAL DE LOS FERROCARRILES NACIONALES' THEN 'FPS FERROCARRILES'
        WHEN "Nombre de la entidad" = 'NUEVA EPS S.A.' THEN 'NUEVA EPS'
        WHEN "Nombre de la entidad" = 'NUEVA EPS S.A. -CM' THEN 'NUEVA EPS'
        WHEN "Nombre de la entidad" = 'PIJAOS SALUD EPSI -CM' THEN 'PIJAOS SALUD EPSI'
        WHEN "Nombre de la entidad" = 'SALUD TOTAL ENTIDAD PROMOTORA DE SALUD DEL REGIMEN CONTRIBUTIVO Y DEL REGIMEN SUBSIDIADO S.A.' THEN 'SALUD TOTAL'
        ELSE "Nombre de la entidad"
    END
WHERE "Nombre de la entidad" IN (
    'ALIANSALUD EPS S.A.',
    'ALIANZA MEDELLIN ANTIOQUIA EPS S.A.S. SAVIA SALUD EPS -CM',
    'ASOCIACIÓN DE CABILDOS INDÍGENAS DEL CESAR Y GUAJIRA DUSAKAWI A.R.S.I. -CM',
    'ASMET SALUD EPS S.A.S. -CM',
    'ASOCIACION MUTUAL SER EMPRESA SOLIDARIA DE SALUD ENTIDAD PROMOTORA DE SALUD - MUTUAL SER EPS',
    'ASOCIACION MUTUAL SER EMPRESA SOLIDARIA DE SALUD ENTIDAD PROMOTORA DE SALUD - MUTUAL SER EPS -CM',
    'CAJACOPI EPS S.A.S -CM',
    'ASOCIACIÓN INDÍGENA DEL CAUCA A.I.C. EPSI -CM',
    'CAJA DE COMPENSACIÓN FAMILIAR COMPENSAR',
    'CAJA DE COMPENSACIÓN FAMILIAR DEL CHOCÓ -CM',
    'CAJA DE COMPENSACIÓN FAMILIAR DEL ORIENTE COLOMBIANO COMFAORIENTE -CM',
    'CAJA DE COMPENSACION FAMILIAR DEL VALLE DEL CAUCA COMFENALCO VALLE DE LA GENTE',
    'CAPITAL SALUD ENTIDAD PROMOTORA DE SALUD DEL RÉGIMEN SUBSIDIADO SAS CAPITAL SALUD EPS-S S.A.S. -CM',
    'CAPRESOCA E.P.S. -CM',
    'COOSALUD EPS S.A.',
    'COOSALUD EPS S.A. -CM',
    'EMPRESA PROMOTORA DE SALUD INDÍGENA ANAS WAYUU EPSI -CM',
    'EMPRESAS PUBLICAS DE MEDELLIN - DEPARTAMENTO MEDICO',
    'EMSSANAR S.A.S. -CM',
    'ENTIDAD PROMOTORA DE SALUD MALLAMAS EPSI -CM',
    'ENTIDAD PROMOTORA DE SALUD SANITAS S.A.S.',
    'ENTIDAD PROMOTORA DE SALUD SERVICIO OCCIDENTAL DE SALUD S.A. S.O.S.',
    'EPS FAMILIAR DE COLOMBIA S.A.S. -CM',
    'EPS FAMISANAR S.A.S.',
    'EPS SURAMERICANA S.A.',
    'FONDO PASIVO SOCIAL DE LOS FERROCARRILES NACIONALES',
    'NUEVA EPS S.A.',
    'NUEVA EPS S.A. -CM',
    'PIJAOS SALUD EPSI -CM',
    'SALUD TOTAL ENTIDAD PROMOTORA DE SALUD DEL REGIMEN CONTRIBUTIVO Y DEL REGIMEN SUBSIDIADO S.A.'
);



-- Standardize entity names in subsidiado table
UPDATE landing.subsidiado
SET "Nombre de la entidad" = 
    CASE
        WHEN "Nombre de la entidad" = 'EPS SURAMERICANA S.A. -CM' THEN 'SURA'
        WHEN "Nombre de la entidad" = 'FUNDACIÓN SALUD MIA -CM' THEN 'SALUD MIA'
        WHEN "Nombre de la entidad" = 'ALIANSALUD EPS S.A. -CM' THEN 'ALIANSALUD'
        WHEN "Nombre de la entidad" = 'ASMET SALUD EPS S.A.S.' THEN 'ASMET SALUD EPS'
        WHEN "Nombre de la entidad" = 'CAJACOPI EPS S.A.S' THEN 'CAJACOPI'
        WHEN "Nombre de la entidad" = 'CAJA DE COMPENSACIÓN FAMILIAR COMPENSAR -CM' THEN 'COMPENSAR'
        WHEN "Nombre de la entidad" = 'CAJA DE COMPENSACION FAMILIAR DEL VALLE DEL CAUCA COMFENALCO VALLE DE LA GENTE -CM' THEN 'COMFENALCO'
        WHEN "Nombre de la entidad" = 'CAPITAL SALUD ENTIDAD PROMOTORA DE SALUD DEL RÉGIMEN SUBSIDIADO SAS CAPITAL SALUD EPS-S S.A.S.' THEN 'CAPITAL SALUD'
        WHEN "Nombre de la entidad" = 'EMPRESA PROMOTORA DE SALUD INDÍGENA ANAS WAYUU EPSI' THEN 'ANAS WAYUU EPSI'
        WHEN "Nombre de la entidad" = 'ENTIDAD PROMOTORA DE SALUD MALLAMAS EPSI' THEN 'MALLAMAS EPSI'
        WHEN "Nombre de la entidad" = 'ENTIDAD PROMOTORA DE SALUD SANITAS S.A.S. -CM' THEN 'SANITAS'
        WHEN "Nombre de la entidad" = 'ENTIDAD PROMOTORA DE SALUD SERVICIO OCCIDENTAL DE SALUD S.A. S.O.S. -CM' THEN 'EPS S.O.S'
        WHEN "Nombre de la entidad" = 'EPS FAMILIAR DE COLOMBIA S.A.S.' THEN 'EPS FAMILIAR DE COLOMBIA'
        WHEN "Nombre de la entidad" = 'EPS FAMISANAR S.A.S. -CM' THEN 'FAMISANAR'
        WHEN "Nombre de la entidad" = 'SALUD TOTAL ENTIDAD PROMOTORA DE SALUD DEL REGIMEN CONTRIBUTIVO Y DEL REGIMEN SUBSIDIADO S.A. -CM' THEN 'SALUD TOTAL'
        WHEN "Nombre de la entidad" = 'ALIANZA MEDELLIN ANTIOQUIA EPS S.A.S. SAVIA SALUD EPS' THEN 'SAVIA SALUD'
        WHEN "Nombre de la entidad" = 'ASOCIACIÓN DE CABILDOS INDÍGENAS DEL CESAR Y GUAJIRA DUSAKAWI A.R.S.I.' THEN 'DUSAKAWI EPSI'
        WHEN "Nombre de la entidad" = 'ASOCIACIÓN INDÍGENA DEL CAUCA A.I.C. EPSI' THEN 'ASOCIACIÓN INDÍGENA DEL CAUCA'
        WHEN "Nombre de la entidad" = 'CAJA DE COMPENSACIÓN FAMILIAR DEL ORIENTE COLOMBIANO COMFAORIENTE' THEN 'COMFAORIENTE'
        WHEN "Nombre de la entidad" = 'CAPRESOCA E.P.S.' THEN 'CAPRESOCA EPS'
        WHEN "Nombre de la entidad" = 'EMSSANAR S.A.S.' THEN 'EMSSANAR'
        WHEN "Nombre de la entidad" = 'CAJA DE COMPENSACIÓN FAMILIAR DEL CHOCÓ' THEN 'COMFACHOCÓ'
        ELSE "Nombre de la entidad"
    END
WHERE "Nombre de la entidad" IN (
    'EPS SURAMERICANA S.A. -CM',
    'FUNDACIÓN SALUD MIA -CM',
    'ALIANSALUD EPS S.A. -CM',
    'ASMET SALUD EPS S.A.S.',
    'CAJACOPI EPS S.A.S',
    'CAJA DE COMPENSACIÓN FAMILIAR COMPENSAR -CM',
    'CAJA DE COMPENSACION FAMILIAR DEL VALLE DEL CAUCA COMFENALCO VALLE DE LA GENTE -CM',
    'CAPITAL SALUD ENTIDAD PROMOTORA DE SALUD DEL RÉGIMEN SUBSIDIADO SAS CAPITAL SALUD EPS-S S.A.S.',
    'EMPRESA PROMOTORA DE SALUD INDÍGENA ANAS WAYUU EPSI',
    'ENTIDAD PROMOTORA DE SALUD MALLAMAS EPSI',
    'ENTIDAD PROMOTORA DE SALUD SANITAS S.A.S. -CM',
    'ENTIDAD PROMOTORA DE SALUD SERVICIO OCCIDENTAL DE SALUD S.A. S.O.S. -CM',
    'EPS FAMILIAR DE COLOMBIA S.A.S.',
    'EPS FAMISANAR S.A.S. -CM',
    'SALUD TOTAL ENTIDAD PROMOTORA DE SALUD DEL REGIMEN CONTRIBUTIVO Y DEL REGIMEN SUBSIDIADO S.A. -CM',
    'ALIANZA MEDELLIN ANTIOQUIA EPS S.A.S. SAVIA SALUD EPS',
    'ASOCIACIÓN DE CABILDOS INDÍGENAS DEL CESAR Y GUAJIRA DUSAKAWI A.R.S.I.',
    'ASOCIACIÓN INDÍGENA DEL CAUCA A.I.C. EPSI',
    'CAJA DE COMPENSACIÓN FAMILIAR DEL ORIENTE COLOMBIANO COMFAORIENTE',
    'CAPRESOCA E.P.S.',
    'EMSSANAR S.A.S.',
    'CAJA DE COMPENSACIÓN FAMILIAR DEL CHOCÓ'
);
